name: search_ugm_mobile
description: Search UGM Digital Services Hub mobile application.
publish_to: none
version: 1.2.0+3

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
